# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:


# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/cacaorick
- slug: twitter
  url: https://twitter.com/cacaorick


#  Add Google analytics tracking ID here
# google_analytics: 

# Banner
banner:
  # Show image in banner
  image: true
  # Show Hitokoto in home page, if false show subtitle or title
  hitokoto: true
  # Banner image use imagelist or lovewallpaper
  customimage: false
  # Banner image list
  imagelist:
  - "/images/banner/k02_03.jpg"
  - "/images/banner/k03_03.jpg" 
  - "/images/banner/w6_1920x1080.jpg"
  - "/images/banner/w12_1920x1080.jpg"